import { test, expect } from '@playwright/test';
import { signInOwner } from './owner-session';

const base = process.env.QA_BASE_URL || 'http://localhost:3100';
test('client applies and removes a proposal discount on mobile', async ({ browser }) => {
  const owner = await browser.newContext();
  await signInOwner(owner, base);
  const client = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await client.newPage();
  page.setDefaultTimeout(20000);
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const suffix = crypto.randomUUID();
  const title = `QA discount proposal ${suffix}`;
  const code = `TEST-${suffix.slice(0, 8)}`.toUpperCase();
  let eventId = '', packageId = '', discountId = '';
  const post = async (path: string, data: Record<string, unknown>) => {
    const response = await owner.request.post(base + path, { headers: { Origin: base }, data });
    if (!response.ok()) throw Error(`${path}: ${response.status()} ${await response.text()}`);
    expect(response.status()).toBe(200);
    return response.json();
  };
  const snapshot = async () => (await owner.request.get(base + '/api/crm')).json();
  try {
    const initial = await snapshot();
    packageId = (await post('/api/crm', { action: 'save_package', name: title, service: initial.business.services[0], price: 50000, duration: '4 hr', description: 'Synthetic QA package', settings: { status: 'Private' } })).savedPackageId;
    const resources = await post('/api/manage', { action: 'save_resource', kind: 'discounts', name: title, data: { code, mode: 'Percentage', amount: 10, allowProposalRedemption: true } });
    discountId = resources.resources.find((r: { name: string; kind: string }) => r.kind === 'discounts' && r.name === title).id;
    const created = await post('/api/crm', { action: 'save_event', initialStatus: 'proposal', title, client: 'Synthetic Client', email: 'qa-client@example.test', date: '2032-05-14', time: '17:00', packageIds: [packageId], deposit: 10000 });
    const original = created.events.find((e: { title: string }) => e.title === title);
    eventId = original.id;
    const shared = await post('/api/proposal', { action: 'share_link', eventId });
    await page.goto(base + shared.path);
    const form = page.getByRole('form', { name: 'Proposal discount' });
    await expect(form).toHaveCount(0);
    const admin = await owner.newPage();
    admin.setDefaultTimeout(20000);
    await admin.goto(base + '/?section=proposals');
    await admin.getByLabel('Search proposals', { exact: true }).fill(title);
    await admin.getByRole('button', { name: `${title} Synthetic Client`, exact: true }).click();
    const visibility = admin.getByRole('switch', { name: 'Show discount code field' });
    await expect(visibility).not.toBeChecked();
    await visibility.click();
    await expect.poll(async () => (await snapshot()).events.find((e: { id: string }) => e.id === eventId).operations.showDiscountCode).toBe(true);
    await page.reload();
    await expect(form).toBeVisible();
    const toggle = form.getByRole('button', { name: 'Have a discount code?' });
    await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    await expect(form.getByLabel('Discount code', { exact: true })).toBeHidden();
    await expect(toggle).toBeEnabled();
    await toggle.focus();
    await toggle.press('Enter');
    await expect(toggle).toHaveAttribute('aria-expanded', 'true');
    await form.getByLabel('Discount code', { exact: true }).fill('DOES-NOT-EXIST');
    await form.getByRole('button', { name: 'Apply code' }).click();
    await expect(form.getByRole('alert')).toContainText('not available');
    expect((await snapshot()).events.find((e: { id: string }) => e.id === eventId).total).toBe(original.total);
    await form.getByLabel('Discount code', { exact: true }).fill(` ${code.toLowerCase()} `);
    const [saved] = await Promise.all([
      page.waitForResponse(response => new URL(response.url()).pathname === '/api/proposal/options' && response.request().method() === 'POST' && response.request().postDataJSON()?.action === 'save'),
      form.getByRole('button', { name: 'Apply code' }).click(),
    ]);
    expect(saved.status(), await saved.text()).toBe(200);
    await expect(form.getByText(code, { exact: true })).toBeVisible();
    await expect(form.getByRole('button', { name: 'Change discount code' })).toHaveAttribute('aria-expanded', 'false');
    await expect(form.getByLabel('Discount code', { exact: true })).toBeHidden();
    let updated = (await snapshot()).events.find((e: { id: string }) => e.id === eventId);
    expect(updated.total).toBeLessThan(original.total);
    expect(updated.operations.quote.discountName).toBe(code);
    expect(updated.status).toBe('proposal');
    expect(updated.deposit).toBe(Math.min(original.deposit, updated.total));
    await expect(page.locator('.proposal-totals')).toContainText(`Discount (${code})`);
    await form.scrollIntoViewIfNeeded();
    await page.screenshot({ path: 'artifacts/proposal-discount-mobile.png', fullPage: false });
    const bounds = await form.boundingBox();
    expect(bounds!.width).toBeLessThanOrEqual(390);
    await page.reload();
    await expect(form.getByText(code, { exact: true })).toBeVisible();
    await expect(visibility).toBeChecked();
    await visibility.click();
    await expect(visibility).not.toBeChecked();
    await expect.poll(async () => (await snapshot()).events.find((e: { id: string }) => e.id === eventId).operations.showDiscountCode).toBe(false);
    await page.reload();
    await expect(form).toHaveCount(0);
    await expect(page.locator('.proposal-totals')).toContainText(`Discount (${code})`);
    expect((await snapshot()).events.find((e: { id: string }) => e.id === eventId).total).toBe(updated.total);
    await admin.locator('.proposal-card').filter({ has: visibility }).scrollIntoViewIfNeeded();
    expect((await visibility.boundingBox())!.width).toBeLessThanOrEqual(48);
    await admin.screenshot({ path: 'artifacts/proposal-discount-visibility.png', fullPage: false });
    await visibility.click();
    await expect(visibility).toBeChecked();
    await expect.poll(async () => (await snapshot()).events.find((e: { id: string }) => e.id === eventId).operations.showDiscountCode).toBe(true);
    await page.reload();
    await expect(form.getByText(code, { exact: true })).toBeVisible();
    await admin.close();
    await form.getByRole('button', { name: 'Change discount code' }).click();
    await expect(form.getByLabel('Discount code', { exact: true })).toHaveValue(code);
    await form.getByRole('button', { name: 'Change discount code' }).click();
    await form.getByRole('button', { name: 'Remove code' }).click();
    await expect(form.getByRole('button', { name: 'Remove code' })).toHaveCount(0);
    await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    await expect(form.getByLabel('Discount code', { exact: true })).toBeHidden();
    updated = (await snapshot()).events.find((e: { id: string }) => e.id === eventId);
    expect(updated.total).toBe(original.total);
    expect(updated.operations.quote.discount).toBe(0);
    expect(updated.operations.quote.discountId).toBe('');
    // Confirmed/expired guards also have API coverage; a deleted link cannot offer this form.
    await post('/api/sales', { action: 'event_lifecycle', ids: [eventId], lifecycle: 'Deleted' });
    await page.reload();
    await expect(form).toHaveCount(0);
    expect(errors).toEqual([]);
  } finally {
    if (eventId) await post('/api/sales', { action: 'event_lifecycle', ids: [eventId], lifecycle: 'Deleted' });
    if (discountId) await post('/api/manage', { action: 'delete_resource', kind: 'discounts', id: discountId, confirm: true });
    if (packageId) await post('/api/packages', { action: 'delete_packages', ids: [packageId], confirm: 'DELETE' });
    await client.close();
    await owner.close();
  }
});
