import './sales-reports.mjs';
import assert from 'node:assert/strict';
const { buildReport, blankReportFilter } = await import('../work/sales-unit/sales-reports.mjs');
const e = (id, patch = {}) => ({ id, title: id, client: 'Alex', email: 'Alex@Example.com', date: '2030-05-01', status: 'confirmed', lifecycle: 'Active', total: 55000, items: [{ id: 'p', name: 'Original', price: 30000 }], operations: { staffIds: ['s', 's'], quote: { extras: [{ id: 'a', name: 'Extra', kind: 'addons', quantity: 3, price: 15000 }, { id: 'a', name: 'Extra', kind: 'addons', quantity: 1, price: 5000 }, { id: 'b', name: 'Backdrop', kind: 'backdrops', quantity: 1, price: 0 }] } }, ...patch });
const data = { packages: [], resources: [{ id: 's', kind: 'staff', name: 'Staff', archived: 1 }], events: [e('one'), e('two', { date: '2030-06-01', client: 'Alex Smith', email: ' alex@example.com ', items: [{ id: 'p', name: 'Renamed', price: 32000 }] }), e('cancelled', { lifecycle: 'Canceled' }), e('lead', { status: 'lead' }), e('proposal', { status: 'proposal' }), e('old', { date: '2029-12-31' })] };
const report = (group, patch = {}) => buildReport(data, 'Most Frequently Booked', { ...blankReportFilter, from: '2030-01-01', to: '2030-12-31', group, ...patch });
assert.deepEqual(report('Packages').rows, [['Renamed', 2, 620]]);
assert.deepEqual(report('Add-ons').rows, [['Extra', 2, 8, 400]], 'Quantity must not multiply an already totaled line price');
assert.deepEqual(report('Backdrops').rows, [['Backdrop', 2, 0]], 'Included backdrop still counts');
assert.deepEqual(report('Staff').rows, [['Staff', 2]], 'Staff counted once per booking, no zero-dollar revenue');
assert.deepEqual(report('Customers').rows, [['Alex Smith (alex@example.com)', 2, 1100]]);
assert.deepEqual(report('Packages').frequencyEntries[0].eventIds, ['two', 'one']);
assert.deepEqual(report('Packages', { columns: ['Bookings'], search: 'renamed' }).rows, [[2]]);
assert.deepEqual(report('Packages', { to: '2030-05-01' }).rows, [['Original', 1, 300]]);
assert.ok(report('Packages', { from: '2031-01-01' }).error);
assert.equal(report('Staff', { search: 'missing' }).rows.length, 0);
data.events = [e('blank1', { email: '' }), e('blank2', { email: '' })];
assert.equal(report('Customers').rows.length, 2, 'Missing emails must not merge unrelated clients');
console.log('PASS frequency tabs: distinct bookings, quantities, renamed IDs, customer email normalization, staff deduplication, saved line values, date/search/columns, drill-down and missing identity.');
