import type { BookingSlot, PricingTier } from './package-pricing';
import type { FormField } from './manage-config';
export type PublicExtra = {
  id: string;
  name: string;
  price: number;
  description: string;
  maxQuantity: number;
  pricingMethod: string;
  leadDays: number;
  images: string[];
  included: boolean;
  category: string;
};
export type AvailableSlot = { time: string; label: string; minutes: number };
export const availabilityPath = (businessId: string) =>
  '/reservation/start?' + new URLSearchParams({ business: businessId });
export type PublicBooking = {
  business: {
    id: string;
    name: string;
    email: string;
    phone: string;
    color: string;
    timezone: string;
    hasLogo: boolean;
  };
  package: {
    id: string;
    name: string;
    description: string;
    service: string;
    price: number;
    subheader: string;
    showTitle: boolean;
    includedMinutes: number;
    minMinutes: number;
    maxMinutes: number;
    increment: number;
    extraHours: boolean;
    extraRate: number;
    unitMode: string;
    unitCalculation: string;
    unitTiers: PricingTier[];
    durationUnit: string;
    extraDays: boolean;
    dailyRate: number;
    predefinedSlots: BookingSlot[];
    slotInterval: number;
    unitLabel: string;
    minUnits: number;
    maxUnits: number;
    dateMode: string;
    picker: string;
    slots: string;
    startTime: string;
    endTime: string;
    days: number[];
    requireBackdrop: boolean;
    allowSkipBackdrop: boolean;
    includedAddonIds: string[];
    bookingMode: string;
    images: { id: string; alt: string }[];
  };
  addons: PublicExtra[];
  backdrops: PublicExtra[];
  questions: FormField[];
  presentation?: {
    headline: string;
    subheading: string;
    background: string;
    image: string;
  };
  privacy: { url: string; required: boolean; text: string; sms: string };
  earliestDate: string;
  latestDate: string;
};
export type BookingInput = {
  date: string;
  time: string;
  minutes: number;
  units: number;
  addonIds: string[];
  addonQuantities?: Record<string, number>;
  answers?: Record<string, string>;
  backdropId: string;
  discountCode: string;
};
export type PublicQuote = {
  packagePrice: number;
  duration: string;
  extras: { name: string; price: number; included: boolean }[];
  adjustment: number;
  discount: number;
  tax: number;
  taxLabel: string;
  travel: number;
  total: number;
  deposit: number;
  terms: string;
  token: string;
};
export type BookingContact = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  title: string;
  venue: string;
  notes: string;
};
